name: Build/Deploy Pipeline

on:
  push:
    branches: [ master ]

jobs:
  build:
    
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
    - name: Install NodeJS
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - run: npm ci
